#!/bin/sh
echo
echo "Aktualni konfigurace pro AdaApp" 
echo "(umisteni: $(readlink adaapp_config_edit_adaapp))"
echo "(zakomentovane radky jsou potlaceny)"
echo
cat adaapp_config_edit_adaapp | grep -v '^;'
