#!/bin/sh
echo
echo "Aktualni konfigurace pro Virtualni Senzory" 
echo "(umisteni: $(readlink adaapp_config_edit_vs))"
echo "(zakomentovane radky jsou potlaceny)"
echo
cat adaapp_config_edit_vs | grep -v '^;'
